In [32]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder, LabelBinarizer

In [33]:
datasetPath = r"D:\Project\BigHomework\DecisionTree\Datasets\MelonDataset2.csv"
datasetNewPath = r"D:\Project\BigHomework\DecisionTree\Datasets\MelonDataset2alpha.csv"

In [28]:
datasetDF = pd.read_csv(filepath_or_buffer=datasetPath, header=0, index_col=None)
print(datasetDF)

    色泽  根蒂  敲声  纹理  脐部  触感  好坏
0   青绿  蜷缩  浊响  清晰  凹陷  硬滑  好瓜
1   乌黑  蜷缩  沉闷  清晰  凹陷  硬滑  好瓜
2   乌黑  蜷缩  浊响  清晰  凹陷  硬滑  好瓜
3   青绿  蜷缩  沉闷  清晰  凹陷  硬滑  好瓜
4   浅白  蜷缩  浊响  清晰  凹陷  硬滑  好瓜
5   青绿  稍蜷  浊响  清晰  稍凹  软粘  好瓜
6   乌黑  稍蜷  浊响  稍糊  稍凹  软粘  好瓜
7   乌黑  稍蜷  浊响  清晰  稍凹  硬滑  好瓜
8   乌黑  稍蜷  沉闷  稍糊  稍凹  硬滑  坏瓜
9   青绿  硬挺  清脆  清晰  平坦  软粘  坏瓜
10  浅白  硬挺  清脆  模糊  平坦  硬滑  坏瓜
11  浅白  蜷缩  浊响  模糊  平坦  软粘  坏瓜
12  青绿  稍蜷  浊响  稍糊  凹陷  硬滑  坏瓜
13  浅白  稍蜷  沉闷  稍糊  凹陷  硬滑  坏瓜
14  乌黑  稍蜷  浊响  清晰  稍凹  软粘  坏瓜
15  浅白  蜷缩  浊响  模糊  平坦  硬滑  坏瓜
16  青绿  蜷缩  沉闷  稍糊  稍凹  硬滑  坏瓜


In [23]:
encLabel = LabelEncoder()
encOnehot = OneHotEncoder()
encOrd = OrdinalEncoder()

In [29]:
for col in datasetDF:
    datasetDF[col] = encLabel.fit_transform(datasetDF[col])
    print(encLabel.classes_)

# print(datasetDF)

['乌黑' '浅白' '青绿']
['硬挺' '稍蜷' '蜷缩']
['沉闷' '浊响' '清脆']
['模糊' '清晰' '稍糊']
['凹陷' '平坦' '稍凹']
['硬滑' '软粘']
['坏瓜' '好瓜']


In [30]:
print(datasetDF)

    色泽  根蒂  敲声  纹理  脐部  触感  好坏
0    2   2   1   1   0   0   1
1    0   2   0   1   0   0   1
2    0   2   1   1   0   0   1
3    2   2   0   1   0   0   1
4    1   2   1   1   0   0   1
5    2   1   1   1   2   1   1
6    0   1   1   2   2   1   1
7    0   1   1   1   2   0   1
8    0   1   0   2   2   0   0
9    2   0   2   1   1   1   0
10   1   0   2   0   1   0   0
11   1   2   1   0   1   1   0
12   2   1   1   2   0   0   0
13   1   1   0   2   0   0   0
14   0   1   1   1   2   1   0
15   1   2   1   0   1   0   0
16   2   2   0   2   2   0   0


In [20]:
encOnehot = OneHotEncoder()
encOrd = OrdinalEncoder()

x = datasetDF['色泽'].to_numpy().reshape(-1,1)

# encOrd.fit(x)
# print(encOrd.transform(x))

encOnehot.fit(x)
print(encOnehot.transform(x).toarray())

# for index, s in enumerate(datasetDF):
#     if index == 0:
#         encOnehot.fit(X=datasetDF[s].to_numpy().reshape(-1,1))
#         print(encOnehot.transform(X=datasetDF[s]).to_numpy().reshape(-1,1))
#         break

[[0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
encLabel = LabelEncoder()


In [93]:
datasetOriginDF = pd.read_csv(datasetNewPath, header=0 ,index_col=None)

print(datasetOriginDF.mode())

datasetOriginDF.fillna(datasetOriginDF.mode(),axis = 1, inplace=True)

print(datasetOriginDF)


   色泽  根蒂  敲声  纹理  脐部  触感 好瓜
0  乌黑  蜷缩  浊响  清晰  凹陷  硬滑  否
     色泽   根蒂   敲声   纹理   脐部   触感 好瓜
0    乌黑   蜷缩   浊响   清晰   凹陷   硬滑  是
1    乌黑   蜷缩   沉闷   清晰   凹陷  NaN  是
2    乌黑   蜷缩  NaN   清晰   凹陷   硬滑  是
3    青绿   蜷缩   沉闷   清晰   凹陷   硬滑  是
4   NaN   蜷缩   浊响   清晰   凹陷   硬滑  是
5    青绿   稍蜷   浊响   清晰  NaN   软粘  是
6    乌黑   稍蜷   浊响   稍糊   稍凹   软粘  是
7    乌黑   稍蜷   浊响  NaN   稍凹   硬滑  是
8    乌黑  NaN   沉闷   稍糊   稍凹   硬滑  否
9    青绿   硬挺   清脆  NaN   平坦   软粘  否
10   浅白   硬挺   清脆   模糊   平坦  NaN  否
11   浅白   蜷缩  NaN   模糊   平坦   软粘  否
12  NaN   稍蜷   浊响   稍糊   凹陷   硬滑  否
13   浅白   稍蜷   沉闷   稍糊   凹陷   硬滑  否
14   乌黑   稍蜷   浊响   清晰  NaN   软粘  否
15   浅白   蜷缩   浊响   模糊   平坦   硬滑  否
16   青绿  NaN   沉闷   稍糊   稍凹   硬滑  否


In [98]:
datasetNewDF = pd.read_csv(datasetNewPath, header=0, index_col=None)

from sklearn.impute import SimpleImputer
imputer_mostfreq = SimpleImputer(strategy="constant", fill_value='sb')
for feature in datasetNewDF:
    print(datasetNewDF[feature].to_list())
    k = imputer_mostfreq.fit_transform(datasetNewDF[feature].to_list())
    print(k)
# datasetNewNdarray = imputer_mostfreq.fit_transform(datasetNewDF)
# print(datasetNewDF)

[nan, '乌黑', '乌黑', '青绿', nan, '青绿', '乌黑', '乌黑', '乌黑', '青绿', '浅白', '浅白', nan, '浅白', '乌黑', '浅白', '青绿']


TypeError: 'float' object is not iterable

In [81]:
for i in range(datasetNewDF.shape[0]):
    datasetNewDF.iloc[i,:] = datasetNewNdarray[i]
print(datasetNewDF)

    色泽  根蒂  敲声  纹理  脐部  触感 好瓜
0   乌黑  蜷缩  浊响  清晰  凹陷  硬滑  是
1   乌黑  蜷缩  沉闷  清晰  凹陷  硬滑  是
2   乌黑  蜷缩  浊响  清晰  凹陷  硬滑  是
3   青绿  蜷缩  沉闷  清晰  凹陷  硬滑  是
4   乌黑  蜷缩  浊响  清晰  凹陷  硬滑  是
5   青绿  稍蜷  浊响  清晰  凹陷  软粘  是
6   乌黑  稍蜷  浊响  稍糊  稍凹  软粘  是
7   乌黑  稍蜷  浊响  清晰  稍凹  硬滑  是
8   乌黑  蜷缩  沉闷  稍糊  稍凹  硬滑  否
9   青绿  硬挺  清脆  清晰  平坦  软粘  否
10  浅白  硬挺  清脆  模糊  平坦  硬滑  否
11  浅白  蜷缩  浊响  模糊  平坦  软粘  否
12  乌黑  稍蜷  浊响  稍糊  凹陷  硬滑  否
13  浅白  稍蜷  沉闷  稍糊  凹陷  硬滑  否
14  乌黑  稍蜷  浊响  清晰  凹陷  软粘  否
15  浅白  蜷缩  浊响  模糊  平坦  硬滑  否
16  青绿  蜷缩  沉闷  稍糊  稍凹  硬滑  否


In [89]:
print(datasetDF)

    色泽  根蒂  敲声  纹理  脐部  触感  好坏
0    2   2   1   1   0   0   1
1    0   2   0   1   0   0   1
2    0   2   1   1   0   0   1
3    2   2   0   1   0   0   1
4    1   2   1   1   0   0   1
5    2   1   1   1   2   1   1
6    0   1   1   2   2   1   1
7    0   1   1   1   2   0   1
8    0   1   0   2   2   0   0
9    2   0   2   1   1   1   0
10   1   0   2   0   1   0   0
11   1   2   1   0   1   1   0
12   2   1   1   2   0   0   0
13   1   1   0   2   0   0   0
14   0   1   1   1   2   1   0
15   1   2   1   0   1   0   0
16   2   2   0   2   2   0   0


In [92]:
for i in datasetDF:
    print(datasetDF[i].value_counts().index[0])
    print(datasetDF[i].value_counts())
    print(datasetDF[i].value_counts().values[0])

2
6
2
8
1
10
1
9
0
7
0
12
0
9


In [82]:
for i in range(datasetNewDF.shape[1]):
    datasetNewDF.iloc[:, i] = encLabel.fit_transform(datasetNewDF.iloc[:, i])
    print(encLabel.classes_)

['乌黑' '浅白' '青绿']
['硬挺' '稍蜷' '蜷缩']
['沉闷' '浊响' '清脆']
['模糊' '清晰' '稍糊']
['凹陷' '平坦' '稍凹']
['硬滑' '软粘']
['否' '是']


In [83]:
print(datasetNewDF)

    色泽  根蒂  敲声  纹理  脐部  触感  好瓜
0    0   2   1   1   0   0   1
1    0   2   0   1   0   0   1
2    0   2   1   1   0   0   1
3    2   2   0   1   0   0   1
4    0   2   1   1   0   0   1
5    2   1   1   1   0   1   1
6    0   1   1   2   2   1   1
7    0   1   1   1   2   0   1
8    0   2   0   2   2   0   0
9    2   0   2   1   1   1   0
10   1   0   2   0   1   0   0
11   1   2   1   0   1   1   0
12   0   1   1   2   0   0   0
13   1   1   0   2   0   0   0
14   0   1   1   1   0   1   0
15   1   2   1   0   1   0   0
16   2   2   0   2   2   0   0


In [37]:
from sklearn.preprocessing import LabelEncoder

In [40]:
labelEncoder = LabelEncoder()
for i in datasetNewDF:
    datasetNewDF[i] = labelEncoder.fit_transform(datasetNewDF[i])
    
print(datasetNewDF)

IndexError: arrays used as indices must be of integer (or boolean) type

In [84]:
mapx = {0:'乌黑',1:'浅白',2:'青绿'}
datasetNewDF['色泽'] = datasetNewDF['色泽'].map(mapx)
print(datasetNewDF['色泽'])

0     乌黑
1     乌黑
2     乌黑
3     青绿
4     乌黑
5     青绿
6     乌黑
7     乌黑
8     乌黑
9     青绿
10    浅白
11    浅白
12    乌黑
13    浅白
14    乌黑
15    浅白
16    青绿
Name: 色泽, dtype: object
